# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30026fcb94cf33dd4b19cdd2585d675db067fa1bf2286c4019bd8212d99c23e7c0a5a480bef4286452d32663c7c404e0c99b91378b419c0eabdfd5aea29c0935

test:
  secret_key_base: cd124353e6c2d931946ca6834d70dce570b0ff33774efb91730ca3b5685669d29126cde1e7393cd317c4d02e6d691578481695be060f667eb6b0545c5fc3665b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
